"""
python manage.py seed
向数据库插入前端测试用的种子数据
"""
from django.core.management.base import BaseCommand
from django.utils import timezone

from core.models import (
    Message,
    Order,
    OrderDetail,
    Product,
    ProductReview,
    ProductFavorite,
    RegisterReview,
    Tag,
    ProductTag,
    UserTagPreference,
    User,
)


# ── 数据定义 ────

USERS = [
    dict(
        user_id="seed_admin001",
        username="admin_root",
        email="a@a.com",
        phone_display=None, 
        encrypted_password="hashed_admin_pw",
        real_name="系统管理员",
        id_card="110101198001010001",
        phone="13800000001",
        address="北京市西城区",
        role=User.RoleChoices.ADMIN,
        register_status=User.RegisterStatusChoices.APPROVED,
    ),
    dict(
        user_id="seed_buyer001",
        username="buyer_alice",
        email="b@a.com",
        phone_display="123333", 
        encrypted_password="hashed_pw",
        real_name="爱丽丝",
        id_card="110101199501010002",
        phone="13900000002",
        address="上海市静安区南京西路100号",
        register_status=User.RegisterStatusChoices.APPROVED,
    ),
    dict(
        user_id="seed_buyer002",
        username="buyer_bob",
        email="c@a.com",
        phone_display="12331441", 
        encrypted_password="hashed_pw",
        real_name="鲍勃",
        id_card="110101199301010003",
        phone="13900000003",
        address="广州市天河区天河路200号",
        register_status=User.RegisterStatusChoices.APPROVED,
    ),
    dict(
        user_id="seed_seller001",
        username="seller_techshop",
        email="d@a.com",
        phone_display=None, 
        encrypted_password="hashed_pw",
        real_name="科技数码店",
        id_card="110101198801010004",
        phone="13700000004",
        address="深圳市南山区科技园1号",
        register_status=User.RegisterStatusChoices.APPROVED,
    ),

    dict(
        user_id="seed_seller002",
        username="seller_newbie",
        email="e@a.com",
        phone_display=None, 
        encrypted_password="hashed_pw",
        real_name="新手卖家",
        id_card="110101200001010005",
        phone="13700000005",
        address="成都市锦江区春熙路88号",
        register_status=User.RegisterStatusChoices.PENDING,
    ),
]

PRODUCTS = [
    dict(
        product_id="seed_prod001",
        product_name="苹果 iPhone 16 Pro",
        category="手机数码",
        description="苹果最新旗舰手机, 256GB, 钛金属机身, 支持Apple Intelligence.",
        image_url="https://picsum.photos/seed/iphone/400/400",
        price="9999.00",
        stock=30,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1000,
        sales_count=50,
        favorite_count=2,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod002",
        product_name="索尼 WH-1000XM5 降噪耳机",
        category="音频设备",
        description="旗舰级主动降噪无线耳机, 续航30小时, 支持LDAC高解析音频.",
        image_url="https://picsum.photos/seed/headphone/400/400",
        price="2499.00",
        stock=50,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=800,
        sales_count=30,
        favorite_count=1,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod003",
        product_name="Cherry MX 机械键盘",
        category="电脑外设",
        description="Cherry MX红轴, 87键紧凑布局, RGB背光, PBT键帽.",
        image_url="https://picsum.photos/seed/keyboard/400/400",
        price="599.00",
        stock=100,
        publisher_id="seed_seller002",
        product_status=Product.StatusChoices.PENDING,
        view_count=200,
        sales_count=0,
        favorite_count=0,
        avg_rating=0.0,
    ),
    dict(
        product_id="seed_prod004",
        product_name="小米手环 7 (旧款)",
        category="智能穿戴",
        description="此商品已停止销售.",
        image_url="https://picsum.photos/seed/band/400/400",
        price="199.00",
        stock=0,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.OFF_SHELF,
        view_count=500,
        sales_count=100,
        favorite_count=0,
        avg_rating=4.2,
    ),
     dict(
        product_id="seed_prod_005",
        product_name="超清全面屏智能手机-6.7英寸AMOLED版",
        category="手机数码",
        description="6.7英寸AMOLED屏幕，搭载高性能处理器，支持5G网络，后置三摄系统。",
        image_url="https://picsum.photos/seed/phone005/400/400",
        price="3299.00",
        stock=150,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1250,
        sales_count=89,
        favorite_count=45,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_006",
        product_name="无线降噪蓝牙耳机-30小时续航版",
        category="音频设备",
        description="主动降噪技术，长达30小时续航，IPX4防水等级，支持语音助手。",
        image_url="https://picsum.photos/seed/headphone006/400/400",
        price="699.00",
        stock=200,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=980,
        sales_count=120,
        favorite_count=67,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_007",
        product_name="机械键盘套装-Cherry轴体RGB版",
        category="电脑外设",
        description="Cherry轴体，RGB背光，全键无冲，人体工学设计，附带腕托。",
        image_url="https://picsum.photos/seed/keyboard007/400/400",
        price="499.00",
        stock=80,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=750,
        sales_count=42,
        favorite_count=31,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_008",
        product_name="智能运动手环-1.47英寸AMOLED屏版",
        category="智能穿戴",
        description="心率监测，血氧检测，多种运动模式，1.47英寸AMOLED屏，7天长续航。",
        image_url="https://picsum.photos/seed/band008/400/400",
        price="249.00",
        stock=300,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1100,
        sales_count=156,
        favorite_count=92,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_009",
        product_name="便携式榨汁机-304不锈钢刀头版",
        category="生活家电",
        description="304不锈钢刀头，一键操作，便携设计，易清洗，USB充电。",
        image_url="https://picsum.photos/seed/juicer009/400/400",
        price="159.00",
        stock=180,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=600,
        sales_count=78,
        favorite_count=40,
        avg_rating=4.2,
    ),
    dict(
        product_id="seed_prod_010",
        product_name="高清运动相机-4K防抖户外版",
        category="手机数码",
        description="4K视频拍摄，防抖技术，防水外壳，超广角镜头，适合户外运动。",
        image_url="https://picsum.photos/seed/camera010/400/400",
        price="1299.00",
        stock=60,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=850,
        sales_count=33,
        favorite_count=28,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_011",
        product_name="桌面蓝牙音箱-360度环绕声版",
        category="音频设备",
        description="360度环绕声，低音增强，支持TWS串联，内置麦克风，12小时播放。",
        image_url="https://picsum.photos/seed/speaker011/400/400",
        price="399.00",
        stock=120,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=720,
        sales_count=55,
        favorite_count=38,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_012",
        product_name="无线静音鼠标-双模人体工学版",
        category="电脑外设",
        description="2.4G/蓝牙双模连接，静音微动，人体工学设计，可调节DPI，长续航。",
        image_url="https://picsum.photos/seed/mouse012/400/400",
        price="129.00",
        stock=250,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=680,
        sales_count=95,
        favorite_count=50,
        avg_rating=4.1,
    ),
    dict(
        product_id="seed_prod_013",
        product_name="智能体脂秤-多数据APP同步版",
        category="智能穿戴",
        description="可测量体重、体脂率、肌肉量等多项数据，APP同步，高精度传感器。",
        image_url="https://picsum.photos/seed/scale013/400/400",
        price="199.00",
        stock=170,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=530,
        sales_count=64,
        favorite_count=35,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_014",
        product_name="迷你空气循环扇-三档静音版",
        category="生活家电",
        description="三档风速，广角送风，低噪音设计，可定时，节能省电。",
        image_url="https://picsum.photos/seed/fan014/400/400",
        price="89.00",
        stock=220,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=490,
        sales_count=110,
        favorite_count=60,
        avg_rating=4.0,
    ),
    dict(
        product_id="seed_prod_015",
        product_name="超薄全面屏智能手机-6.7英寸AMOLED版",
        category="手机数码",
        description="6.7英寸AMOLED屏幕，搭载高性能处理器，支持5G网络，后置三摄系统。",
        image_url="https://picsum.photos/seed/phone015/400/400",
        price="3299.99",
        stock=85,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1250,
        sales_count=320,
        favorite_count=180,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_016",
        product_name="无线降噪蓝牙耳机-舒适佩戴版",
        category="音频设备",
        description="主动降噪技术，长达30小时续航，IPX4防水等级，舒适佩戴。",
        image_url="https://picsum.photos/seed/headphone016/400/400",
        price="699.50",
        stock=150,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=980,
        sales_count=410,
        favorite_count=220,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_017",
        product_name="机械键盘（青轴）-104键RGB版",
        category="电脑外设",
        description="104键全尺寸，RGB背光，青轴手感清脆，适合打字和游戏。",
        image_url="https://picsum.photos/seed/keyboard017/400/400",
        price="449.00",
        stock=60,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=760,
        sales_count=190,
        favorite_count=95,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_018",
        product_name="智能运动手环-1.47英寸AMOLED屏版",
        category="智能穿戴",
        description="心率监测、睡眠分析、多种运动模式，1.47英寸AMOLED屏幕。",
        image_url="https://picsum.photos/seed/band018/400/400",
        price="199.99",
        stock=200,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1120,
        sales_count=520,
        favorite_count=310,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_019",
        product_name="便携式榨汁机-随身杯户外版",
        category="生活家电",
        description="快速榨汁，易清洗，USB充电，随身杯设计，适合户外使用。",
        image_url="https://picsum.photos/seed/juicer019/400/400",
        price="159.00",
        stock=110,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=540,
        sales_count=230,
        favorite_count=120,
        avg_rating=4.2,
    ),
    dict(
        product_id="seed_prod_020",
        product_name="平板电脑（10英寸）-2K四扬声器版",
        category="手机数码",
        description="2K分辨率屏幕，四扬声器，支持触控笔，适合学习和娱乐。",
        image_url="https://picsum.photos/seed/tablet020/400/400",
        price="1899.00",
        stock=45,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=890,
        sales_count=180,
        favorite_count=85,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_021",
        product_name="蓝牙便携音箱-IP67防水版",
        category="音频设备",
        description="360度环绕音效，IP67防水防尘，续航12小时，支持语音助手。",
        image_url="https://picsum.photos/seed/speaker021/400/400",
        price="299.99",
        stock=175,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=670,
        sales_count=290,
        favorite_count=150,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_022",
        product_name="无线游戏鼠标-轻量化高精度版",
        category="电脑外设",
        description="轻量化设计，高精度传感器，可编程按键，超长电池寿命。",
        image_url="https://picsum.photos/seed/mouse022/400/400",
        price="329.00",
        stock=90,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=720,
        sales_count=210,
        favorite_count=110,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_023",
        product_name="智能翻译耳机-40种语言实时版",
        category="智能穿戴",
        description="实时语音翻译，支持40多种语言，降噪通话，便携充电盒。",
        image_url="https://picsum.photos/seed/translate023/400/400",
        price="899.00",
        stock=30,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=430,
        sales_count=95,
        favorite_count=65,
        avg_rating=4.1,
    ),
    dict(
        product_id="seed_prod_024",
        product_name="空气循环扇-多档静音节能版",
        category="生活家电",
        description="多档风速调节，广角送风，静音设计，节能省电，四季可用。",
        image_url="https://picsum.photos/seed/fan024/400/400",
        price="249.50",
        stock=130,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=610,
        sales_count=170,
        favorite_count=90,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_025",
        product_name="极速游戏鼠标-电竞RGB版",
        category="电脑外设",
        description="高精度传感器，可编程按键，RGB灯效，专为电竞设计。",
        image_url="https://picsum.photos/seed/mouse025/400/400",
        price="299.00",
        stock=150,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1250,
        sales_count=89,
        favorite_count=45,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_026",
        product_name="降噪蓝牙耳机-高清音质版",
        category="音频设备",
        description="主动降噪技术，长续航，舒适佩戴，高清音质。",
        image_url="https://picsum.photos/seed/headphone026/400/400",
        price="899.00",
        stock=80,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3200,
        sales_count=210,
        favorite_count=120,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod_027",
        product_name="智能运动手环-防水运动版",
        category="智能穿戴",
        description="心率监测，睡眠分析，多种运动模式，防水设计。",
        image_url="https://picsum.photos/seed/band027/400/400",
        price="199.00",
        stock=300,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1800,
        sales_count=340,
        favorite_count=95,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_028",
        product_name="便携式投影仪-高清无线投屏版",
        category="生活家电",
        description="小巧便携，高清投影，内置电池，支持无线投屏。",
        image_url="https://picsum.photos/seed/projector028/400/400",
        price="1299.00",
        stock=45,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=950,
        sales_count=32,
        favorite_count=28,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_029",
        product_name="旗舰智能手机-顶级处理器版",
        category="手机数码",
        description="顶级处理器，超清摄像头，大容量电池，5G网络。",
        image_url="https://picsum.photos/seed/phone029/400/400",
        price="5999.00",
        stock=60,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=5000,
        sales_count=150,
        favorite_count=300,
        avg_rating=4.9,
    ),
    dict(
        product_id="seed_prod_030",
        product_name="机械键盘-青轴背光版",
        category="电脑外设",
        description="青轴手感，全键无冲，背光设计，耐用材质。",
        image_url="https://picsum.photos/seed/keyboard030/400/400",
        price="499.00",
        stock=120,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2100,
        sales_count=110,
        favorite_count=65,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_031",
        product_name="无线蓝牙音箱-IPX7防水版",
        category="音频设备",
        description="360度环绕音效，IPX7防水，便携设计，长续航。",
        image_url="https://picsum.photos/seed/speaker031/400/400",
        price="399.00",
        stock=200,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1400,
        sales_count=180,
        favorite_count=80,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_032",
        product_name="智能手表-全面健康监测版",
        category="智能穿戴",
        description="全面健康监测，GPS定位，NFC支付，多种表盘。",
        image_url="https://picsum.photos/seed/watch032/400/400",
        price="1499.00",
        stock=75,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2800,
        sales_count=95,
        favorite_count=150,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod_033",
        product_name="空气净化器-高效智能感应版",
        category="生活家电",
        description="高效过滤，智能感应，低噪音运行，适用大面积。",
        image_url="https://picsum.photos/seed/airpurifier033/400/400",
        price="899.00",
        stock=50,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1100,
        sales_count=40,
        favorite_count=35,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_034",
        product_name="平板电脑-高清大屏轻薄版",
        category="手机数码",
        description="高性能芯片，高清大屏，支持触控笔，轻薄设计。",
        image_url="https://picsum.photos/seed/tablet034/400/400",
        price="3299.00",
        stock=90,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2600,
        sales_count=75,
        favorite_count=110,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_035",
        product_name="极光蓝无线蓝牙耳机-Hi-Fi音质版",
        category="音频设备",
        description="主动降噪，超长续航，Hi-Fi音质，舒适佩戴。",
        image_url="https://picsum.photos/seed/earphone035/400/400",
        price="299.99",
        stock=150,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1250,
        sales_count=320,
        favorite_count=89,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_036",
        product_name="幻影黑游戏机械键盘-金属面板版",
        category="电脑外设",
        description="RGB背光，青轴手感，全键无冲，金属面板。",
        image_url="https://picsum.photos/seed/keyboard036/400/400",
        price="459.00",
        stock=80,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2100,
        sales_count=145,
        favorite_count=67,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_037",
        product_name="智享系列智能手表-两周续航版",
        category="智能穿戴",
        description="心率监测，GPS定位，50米防水，两周续航。",
        image_url="https://picsum.photos/seed/watch037/400/400",
        price="799.50",
        stock=200,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1800,
        sales_count=410,
        favorite_count=120,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_038",
        product_name="清风系列空气净化器-APP控制版",
        category="生活家电",
        description="高效滤网，静音运行，APP控制，适用50平米。",
        image_url="https://picsum.photos/seed/airpurifier038/400/400",
        price="1299.00",
        stock=45,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=950,
        sales_count=85,
        favorite_count=32,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_039",
        product_name="星耀版智能手机-1亿像素主摄版",
        category="手机数码",
        description="6.7英寸AMOLED屏，1亿像素主摄，骁龙8系处理器。",
        image_url="https://picsum.photos/seed/phone039/400/400",
        price="3299.00",
        stock=120,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3500,
        sales_count=280,
        favorite_count=210,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod_040",
        product_name="云影便携式投影仪-1080P自动对焦版",
        category="生活家电",
        description="1080P高清，自动对焦，内置电池，便携户外影院。",
        image_url="https://picsum.photos/seed/projector040/400/400",
        price="1699.00",
        stock=60,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1100,
        sales_count=95,
        favorite_count=45,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_041",
        product_name="雷霆高速移动固态硬盘-1TB USB3.2版",
        category="电脑外设",
        description="1TB容量，USB 3.2接口，读写速度超1000MB/s。",
        image_url="https://picsum.photos/seed/ssd041/400/400",
        price="699.00",
        stock=180,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1400,
        sales_count=220,
        favorite_count=78,
        avg_rating=4.9,
    ),
    dict(
        product_id="seed_prod_042",
        product_name="悦动无线运动耳机-防汗磁吸12小时版",
        category="音频设备",
        description="防汗防水，磁吸设计，12小时播放，运动伴侣。",
        image_url="https://picsum.photos/seed/sportheadphone042/400/400",
        price="199.00",
        stock=300,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=900,
        sales_count=180,
        favorite_count=55,
        avg_rating=4.2,
    ),
    dict(
        product_id="seed_prod_043",
        product_name="智控多功能料理机-破壁加热12菜单版",
        category="生活家电",
        description="破壁加热，自动清洗，12种菜单，厨房好帮手。",
        image_url="https://picsum.photos/seed/blender043/400/400",
        price="899.00",
        stock=70,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=750,
        sales_count=60,
        favorite_count=25,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_044",
        product_name="光影4K高清摄像头-自动对焦降噪版",
        category="电脑外设",
        description="自动对焦，降噪麦克风，广角镜头，直播会议优选。",
        image_url="https://picsum.photos/seed/webcam044/400/400",
        price="499.00",
        stock=110,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1300,
        sales_count=150,
        favorite_count=40,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_045",
        product_name="极光无线蓝牙耳机-主动降噪30小时版",
        category="音频设备",
        description="主动降噪，Hi-Fi音质，超长续航30小时，舒适佩戴。",
        image_url="https://picsum.photos/seed/aurora045/400/400",
        price="499.00",
        stock=150,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3200,
        sales_count=450,
        favorite_count=210,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_046",
        product_name="幻影游戏机械键盘-RGB青轴金属版",
        category="电脑外设",
        description="RGB炫彩背光，青轴手感，全键无冲，金属面板。",
        image_url="https://picsum.photos/seed/phantom046/400/400",
        price="299.00",
        stock=89,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=5100,
        sales_count=620,
        favorite_count=340,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod_047",
        product_name="智慧全面屏智能手机-6.7英寸1亿像素版",
        category="手机数码",
        description="6.7英寸AMOLED屏，旗舰处理器，1亿像素主摄，67W快充。",
        image_url="https://picsum.photos/seed/smartphone047/400/400",
        price="3299.00",
        stock=75,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=8900,
        sales_count=310,
        favorite_count=520,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_048",
        product_name="灵动智能运动手环-心率血氧14天版",
        category="智能穿戴",
        description="心率监测，血氧检测，50米防水，14天续航，多种运动模式。",
        image_url="https://picsum.photos/seed/band048/400/400",
        price="199.00",
        stock=300,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=4300,
        sales_count=880,
        favorite_count=410,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_049",
        product_name="静音无线办公鼠标-人体工学双模版",
        category="电脑外设",
        description="人体工学设计，2.4G/蓝牙双模，超长待机，便携小巧。",
        image_url="https://picsum.photos/seed/mouse049/400/400",
        price="89.00",
        stock=420,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2800,
        sales_count=950,
        favorite_count=180,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_050",
        product_name="便携迷你投影仪-1080P自动对焦版",
        category="生活家电",
        description="1080P高清，内置电池，自动对焦，支持侧投，家庭影院。",
        image_url="https://picsum.photos/seed/projector050/400/400",
        price="1299.00",
        stock=60,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3700,
        sales_count=190,
        favorite_count=260,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_051",
        product_name="高清行车记录仪-前后双录GPS版",
        category="手机数码",
        description="前后双录，GPS定位，停车监控，夜视增强，广角镜头。",
        image_url="https://picsum.photos/seed/dashcam051/400/400",
        price="399.00",
        stock=180,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2900,
        sales_count=420,
        favorite_count=150,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_052",
        product_name="桌面蓝牙音箱-360°环绕IPX7防水版",
        category="音频设备",
        description="360°环绕声，IPX7防水，20小时播放，支持TWS串联。",
        image_url="https://picsum.photos/seed/speaker052/400/400",
        price="259.00",
        stock=200,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3400,
        sales_count=510,
        favorite_count=230,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_053",
        product_name="多功能空气炸锅-5.5L触控屏版",
        category="生活家电",
        description="5.5L大容量，触控屏，无油烹饪，8种预设菜单，易清洗。",
        image_url="https://picsum.photos/seed/airfryer053/400/400",
        price="459.00",
        stock=120,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=5200,
        sales_count=680,
        favorite_count=390,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod_054",
        product_name="智能翻译耳机-实时多语言降噪版",
        category="智能穿戴",
        description="实时多语言翻译，降噪通话，轻便设计，适合旅行商务。",
        image_url="https://picsum.photos/seed/translate054/400/400",
        price="899.00",
        stock=95,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=4100,
        sales_count=240,
        favorite_count=310,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_055",
        product_name="无线蓝牙耳机-高保真主动降噪版",
        category="音频设备",
        description="高保真音质，主动降噪，超长续航，舒适佩戴。",
        image_url="https://picsum.photos/seed/earphone055/400/400",
        price="299.99",
        stock=150,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1250,
        sales_count=320,
        favorite_count=89,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_056",
        product_name="游戏机械键盘-RGB青轴电竞版",
        category="电脑外设",
        description="RGB背光，青轴手感，全键无冲，专为游戏设计。",
        image_url="https://picsum.photos/seed/keyboard056/400/400",
        price="199.50",
        stock=80,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=980,
        sales_count=210,
        favorite_count=45,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_057",
        product_name="智能运动手环-心率睡眠防水版",
        category="智能穿戴",
        description="心率监测，睡眠分析，多种运动模式，防水设计。",
        image_url="https://picsum.photos/seed/band057/400/400",
        price="89.99",
        stock=300,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2100,
        sales_count=560,
        favorite_count=120,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_058",
        product_name="便携式蓝牙音箱-360度IPX7防水版",
        category="音频设备",
        description="360度环绕音效，IPX7防水，续航长达15小时。",
        image_url="https://picsum.photos/seed/speaker058/400/400",
        price="149.99",
        stock=120,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=870,
        sales_count=190,
        favorite_count=38,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_059",
        product_name="高速固态硬盘-NVMe 1TB五年质保版",
        category="电脑外设",
        description="NVMe协议，读写速度超快，1TB大容量，五年质保。",
        image_url="https://picsum.photos/seed/ssd059/400/400",
        price="129.99",
        stock=200,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1450,
        sales_count=410,
        favorite_count=95,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod_060",
        product_name="智能空气净化器-高效过滤APP控制版",
        category="生活家电",
        description="高效过滤PM2.5，静音运行，APP远程控制，适用大面积。",
        image_url="https://picsum.photos/seed/airpurifier060/400/400",
        price="459.99",
        stock=60,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=760,
        sales_count=130,
        favorite_count=25,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_061",
        product_name="智能手机-旗舰5G全网通版",
        category="手机数码",
        description="旗舰处理器，超清摄像头，大容量电池，5G全网通。",
        image_url="https://picsum.photos/seed/phone061/400/400",
        price="899.99",
        stock=90,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3200,
        sales_count=780,
        favorite_count=210,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_062",
        product_name="无线充电鼠标垫-Qi标准RGB版",
        category="电脑外设",
        description="支持Qi标准，鼠标键盘无线充电，RGB氛围灯。",
        image_url="https://picsum.photos/seed/mousepad062/400/400",
        price="79.99",
        stock=180,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=540,
        sales_count=95,
        favorite_count=18,
        avg_rating=4.2,
    ),
    dict(
        product_id="seed_prod_063",
        product_name="智能体脂秤-精准测量APP连接版",
        category="智能穿戴",
        description="精准测量体脂率，连接APP记录数据，高颜值设计。",
        image_url="https://picsum.photos/seed/scale063/400/400",
        price="59.99",
        stock=250,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=690,
        sales_count=180,
        favorite_count=32,
        avg_rating=4.1,
    ),
    dict(
        product_id="seed_prod_064",
        product_name="便携式榨汁机-一键操作USB充电版",
        category="生活家电",
        description="一键操作，快速榨汁，易清洗，USB充电便携。",
        image_url="https://picsum.photos/seed/juicer064/400/400",
        price="39.99",
        stock=400,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1100,
        sales_count=340,
        favorite_count=75,
        avg_rating=4.0,
    ),

    dict(
        product_id="seed_prod_065",
        product_name="旗舰智能手机-顶级摄像头超长续航版",
        category="手机数码",
        description="高性能旗舰手机，配备顶级摄像头和超长续航。",
        image_url="https://picsum.photos/seed/seed_prod_065/400/400",
        price="6999.00",
        stock=150,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3200,
        sales_count=450,
        favorite_count=210,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_066",
        product_name="无线降噪耳机-主动降噪高保真版",
        category="音频设备",
        description="主动降噪，高保真音质，舒适佩戴。",
        image_url="https://picsum.photos/seed/seed_prod_066/400/400",
        price="899.00",
        stock=300,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2800,
        sales_count=620,
        favorite_count=180,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_067",
        product_name="机械键盘-RGB青轴全键无冲版",
        category="电脑外设",
        description="RGB背光，青轴手感，全键无冲。",
        image_url="https://picsum.photos/seed/seed_prod_067/400/400",
        price="499.00",
        stock=200,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1900,
        sales_count=310,
        favorite_count=95,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_068",
        product_name="智能手表-健康监测长续航版",
        category="智能穿戴",
        description="健康监测，运动追踪，长续航。",
        image_url="https://picsum.photos/seed/seed_prod_068/400/400",
        price="1299.00",
        stock=180,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2500,
        sales_count=380,
        favorite_count=150,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_069",
        product_name="空气净化器-高效过滤智能感应版",
        category="生活家电",
        description="高效过滤，智能感应，静音运行。",
        image_url="https://picsum.photos/seed/seed_prod_069/400/400",
        price="1599.00",
        stock=120,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1700,
        sales_count=240,
        favorite_count=110,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_070",
        product_name="平板电脑-大屏轻薄性能版",
        category="手机数码",
        description="大屏娱乐，轻薄设计，性能强劲。",
        image_url="https://picsum.photos/seed/seed_prod_070/400/400",
        price="3299.00",
        stock=220,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2100,
        sales_count=290,
        favorite_count=130,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_071",
        product_name="蓝牙音箱-便携立体声防水版",
        category="音频设备",
        description="便携设计，立体声音效，防水防尘。",
        image_url="https://picsum.photos/seed/seed_prod_071/400/400",
        price="299.00",
        stock=400,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1500,
        sales_count=520,
        favorite_count=85,
        avg_rating=4.2,
    ),
    dict(
        product_id="seed_prod_072",
        product_name="电竞鼠标-高精度可编程轻量版",
        category="电脑外设",
        description="高精度传感器，可编程按键，轻量化设计。",
        image_url="https://picsum.photos/seed/seed_prod_072/400/400",
        price="399.00",
        stock=250,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1800,
        sales_count=340,
        favorite_count=100,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_073",
        product_name="智能手环-心率睡眠消息提醒版",
        category="智能穿戴",
        description="心率监测，睡眠分析，消息提醒。",
        image_url="https://picsum.photos/seed/seed_prod_073/400/400",
        price="199.00",
        stock=500,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2300,
        sales_count=680,
        favorite_count=170,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_074",
        product_name="咖啡机-全自动多口味易清洗版",
        category="生活家电",
        description="全自动制作，多种口味选择，易清洗。",
        image_url="https://picsum.photos/seed/seed_prod_074/400/400",
        price="899.00",
        stock=90,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1400,
        sales_count=160,
        favorite_count=75,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_075",
        product_name="无线降噪耳机-主动降噪30小时续航版",
        category="音频设备",
        description="主动降噪技术，高保真音质，续航长达30小时。",
        image_url="https://picsum.photos/seed/audio075/400/400",
        price="899.00",
        stock=150,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3200,
        sales_count=450,
        favorite_count=210,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_076",
        product_name="游戏机械键盘-RGB青轴电竞设计版",
        category="电脑外设",
        description="RGB背光，青轴手感，全键无冲，专为电竞设计。",
        image_url="https://picsum.photos/seed/keyboard076/400/400",
        price="499.00",
        stock=85,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2800,
        sales_count=310,
        favorite_count=180,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_077",
        product_name="智能运动手环-心率防水运动模式版",
        category="智能穿戴",
        description="心率监测，睡眠分析，多种运动模式，防水设计。",
        image_url="https://picsum.photos/seed/band077/400/400",
        price="199.00",
        stock=300,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=4100,
        sales_count=890,
        favorite_count=340,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_078",
        product_name="便携式蓝牙音箱-360度IPX7 12小时版",
        category="音频设备",
        description="360度环绕音效，IPX7防水，续航12小时，便携设计。",
        image_url="https://picsum.photos/seed/speaker078/400/400",
        price="299.00",
        stock=120,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1900,
        sales_count=270,
        favorite_count=95,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_079",
        product_name="高速固态硬盘-NVMe 3500MB/s 1TB版",
        category="电脑外设",
        description="NVMe协议，读取速度高达3500MB/s，1TB容量。",
        image_url="https://picsum.photos/seed/ssd079/400/400",
        price="649.00",
        stock=60,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2200,
        sales_count=180,
        favorite_count=110,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod_080",
        product_name="智能空气净化器-高效过滤50㎡适用版",
        category="生活家电",
        description="高效过滤PM2.5，智能感应，静音运行，适用面积50㎡。",
        image_url="https://picsum.photos/seed/air080/400/400",
        price="1299.00",
        stock=45,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1500,
        sales_count=120,
        favorite_count=75,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_081",
        product_name="旗舰智能手机-6.7英寸AMOLED版",
        category="手机数码",
        description="6.7英寸AMOLED屏幕，旗舰处理器，1亿像素主摄。",
        image_url="https://picsum.photos/seed/phone081/400/400",
        price="3999.00",
        stock=200,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=8500,
        sales_count=650,
        favorite_count=520,
        avg_rating=4.9,
    ),
    dict(
        product_id="seed_prod_082",
        product_name="无线充电鼠标垫-Qi充电RGB版",
        category="电脑外设",
        description="支持Qi无线充电，RGB灯效，大尺寸游戏鼠标垫。",
        image_url="https://picsum.photos/seed/mousepad082/400/400",
        price="349.00",
        stock=110,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1300,
        sales_count=90,
        favorite_count=60,
        avg_rating=4.2,
    ),
    dict(
        product_id="seed_prod_083",
        product_name="智能体脂秤-APP同步版",
        category="智能穿戴",
        description="可测量体重、体脂率、肌肉量等多项身体数据，APP同步。",
        image_url="https://picsum.photos/seed/scale083/400/400",
        price="159.00",
        stock=180,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1100,
        sales_count=230,
        favorite_count=85,
        avg_rating=4.0,
    ),
    dict(
        product_id="seed_prod_084",
        product_name="便携式榨汁机-一键操作便携杯版",
        category="生活家电",
        description="一键操作，快速榨汁，便携杯设计，易于清洗。",
        image_url="https://picsum.photos/seed/juicer084/400/400",
        price="179.00",
        stock=250,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=900,
        sales_count=140,
        favorite_count=50,
        avg_rating=4.1,
    ),
    dict(
        product_id="seed_prod_085",
        product_name="极光无线蓝牙耳机-主动降噪Hi-Fi版",
        category="音频设备",
        description="主动降噪，超长续航，Hi-Fi音质，舒适佩戴。",
        image_url="https://picsum.photos/seed/aurora085/400/400",
        price="299.99",
        stock=150,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1250,
        sales_count=320,
        favorite_count=89,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_086",
        product_name="幻影电竞机械键盘-青轴RGB版",
        category="电脑外设",
        description="RGB背光，青轴手感，全键无冲，金属面板。",
        image_url="https://picsum.photos/seed/phantom086/400/400",
        price="459.00",
        stock=85,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2100,
        sales_count=180,
        favorite_count=120,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod_087",
        product_name="灵动智能手环-7天长续航版",
        category="智能穿戴",
        description="心率监测，睡眠分析，消息提醒，7天长续航。",
        image_url="https://picsum.photos/seed/vital087/400/400",
        price="199.50",
        stock=300,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=980,
        sales_count=410,
        favorite_count=65,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_088",
        product_name="星云全面屏手机-1亿像素旗舰版",
        category="手机数码",
        description="6.7英寸AMOLED，1亿像素主摄，旗舰处理器。",
        image_url="https://picsum.photos/seed/nebula088/400/400",
        price="3299.00",
        stock=60,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3500,
        sales_count=95,
        favorite_count=210,
        avg_rating=4.9,
    ),
    dict(
        product_id="seed_prod_089",
        product_name="静音空气循环扇-直流变频遥控版",
        category="生活家电",
        description="直流变频，广角送风，遥控操作，节能省电。",
        image_url="https://picsum.photos/seed/breeze089/400/400",
        price="289.00",
        stock=200,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=760,
        sales_count=280,
        favorite_count=45,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_090",
        product_name="疾风游戏鼠标-16000DPI轻量化版",
        category="电脑外设",
        description="16000 DPI，轻量化设计，6个可编程按键。",
        image_url="https://picsum.photos/seed/gale090/400/400",
        price="189.00",
        stock=175,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1420,
        sales_count=230,
        favorite_count=78,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_091",
        product_name="全景运动相机-4K防抖超广角版",
        category="手机数码",
        description="4K录制，防抖防水，超广角镜头，便携设计。",
        image_url="https://picsum.photos/seed/action091/400/400",
        price="899.00",
        stock=40,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1850,
        sales_count=110,
        favorite_count=95,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_092",
        product_name="智慧蓝牙音箱-360°环绕声防水版",
        category="音频设备",
        description="360°环绕声，语音助手，IPX7防水，12小时续航。",
        image_url="https://picsum.photos/seed/harmony092/400/400",
        price="399.00",
        stock=120,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1100,
        sales_count=190,
        favorite_count=52,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_093",
        product_name="智控加湿器-大容量UV杀菌版",
        category="生活家电",
        description="大容量，静音运行，智能恒湿，UV杀菌。",
        image_url="https://picsum.photos/seed/mist093/400/400",
        price="249.00",
        stock=180,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=670,
        sales_count=155,
        favorite_count=30,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_094",
        product_name="曜石智能手表-eSIM通话陶瓷版",
        category="智能穿戴",
        description="eSIM通话，健康监测，运动模式，陶瓷机身。",
        image_url="https://picsum.photos/seed/obsidian094/400/400",
        price="1299.00",
        stock=75,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2400,
        sales_count=85,
        favorite_count=140,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod_095",
        product_name="极光无线耳机-主动降噪30小时续航版",
        category="音频设备",
        description="主动降噪，30小时续航，Hi-Res认证，蓝牙5.2",
        image_url="https://picsum.photos/seed/aurora095/400/400",
        price="899.00",
        stock=150,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3200,
        sales_count=450,
        favorite_count=210,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_096",
        product_name="幻影游戏鼠标-26000DPI RGB版",
        category="电脑外设",
        description="26000DPI，RGB灯效，轻量化设计，8个可编程按键",
        image_url="https://picsum.photos/seed/phantom096/400/400",
        price="299.00",
        stock=200,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2800,
        sales_count=380,
        favorite_count=180,
        avg_rating=4.5,
    ),
    dict(
        product_id="seed_prod_097",
        product_name="智慧手环7-1.47英寸AMOLED版",
        category="智能穿戴",
        description="1.47英寸AMOLED屏，血氧心率监测，50米防水，14天续航",
        image_url="https://picsum.photos/seed/band097/400/400",
        price="249.00",
        stock=300,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=4100,
        sales_count=520,
        favorite_count=290,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_098",
        product_name="旋风无线吸尘器-150AW除螨版",
        category="生活家电",
        description="150AW吸力，60分钟续航，五重过滤，可除螨",
        image_url="https://picsum.photos/seed/vacuum098/400/400",
        price="1299.00",
        stock=80,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1900,
        sales_count=110,
        favorite_count=85,
        avg_rating=4.4,
    ),
    dict(
        product_id="seed_prod_099",
        product_name="星耀智能手机-骁龙8+ 5000mAh版",
        category="手机数码",
        description="6.7英寸AMOLED，1亿像素主摄，骁龙8+处理器，5000mAh电池",
        image_url="https://picsum.photos/seed/star099/400/400",
        price="3499.00",
        stock=120,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=5600,
        sales_count=310,
        favorite_count=340,
        avg_rating=4.8,
    ),
    dict(
        product_id="seed_prod_100",
        product_name="雷霆机械键盘-Cherry红轴PBT版",
        category="电脑外设",
        description="Cherry红轴，RGB背光，PBT键帽，全键无冲",
        image_url="https://picsum.photos/seed/thunder100/400/400",
        price="599.00",
        stock=180,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3400,
        sales_count=270,
        favorite_count=155,
        avg_rating=4.6,
    ),
    dict(
        product_id="seed_prod_101",
        product_name="便携蓝牙音箱-IPX7防水20小时版",
        category="音频设备",
        description="360°环绕声，IPX7防水，20小时播放，支持TWS串联",
        image_url="https://picsum.photos/seed/speaker101/400/400",
        price="399.00",
        stock=220,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=2700,
        sales_count=190,
        favorite_count=120,
        avg_rating=4.3,
    ),
    dict(
        product_id="seed_prod_102",
        product_name="无雾加湿器-4L大容量UV杀菌版",
        category="生活家电",
        description="4L大容量，UV杀菌，智能恒湿，静音运行",
        image_url="https://picsum.photos/seed/humidifier102/400/400",
        price="369.00",
        stock=160,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=1800,
        sales_count=95,
        favorite_count=70,
        avg_rating=4.2,
    ),
    dict(
        product_id="seed_prod_103",
        product_name="智能运动手表-双频GPS百种运动版",
        category="智能穿戴",
        description="1.3英寸圆形屏，双频GPS，100+运动模式，健康管理",
        image_url="https://picsum.photos/seed/watch103/400/400",
        price="899.00",
        stock=90,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=3800,
        sales_count=180,
        favorite_count=200,
        avg_rating=4.7,
    ),
    dict(
        product_id="seed_prod_104",
        product_name="超薄平板电脑-11英寸2.5K四扬声器版",
        category="手机数码",
        description="11英寸2.5K屏，骁龙870，四扬声器，支持手写笔",
        image_url="https://picsum.photos/seed/tablet104/400/400",
        price="2399.00",
        stock=70,
        publisher_id="seed_seller001",
        product_status=Product.StatusChoices.APPROVED,
        view_count=4200,
        sales_count=130,
        favorite_count=175,
        avg_rating=4.5,
    ),
]

REGISTER_REVIEWS = [
    dict(
        review_id="seed_rr001",
        pending_user_id="seed_buyer001",
        admin_id="seed_admin001",
        result=RegisterReview.ResultChoices.APPROVED,
        opinion="资料齐全, 审核通过.",
    ),
    dict(
        review_id="seed_rr002",
        pending_user_id="seed_buyer002",
        admin_id="seed_admin001",
        result=RegisterReview.ResultChoices.APPROVED,
        opinion="审核通过.",
    ),
    dict(
        review_id="seed_rr003",
        pending_user_id="seed_seller001",
        admin_id="seed_admin001",
        result=RegisterReview.ResultChoices.APPROVED,
        opinion="营业执照已核实, 审核通过.",
    ),
]

PRODUCT_REVIEWS = [
    dict(
        review_id="seed_pr001",
        pending_product_id="seed_prod001",
        admin_id="seed_admin001",
        result=ProductReview.ResultChoices.APPROVED,
        opinion="商品描述真实, 价格合理, 审核通过.",
    ),
    dict(
        review_id="seed_pr002",
        pending_product_id="seed_prod002",
        admin_id="seed_admin001",
        result=ProductReview.ResultChoices.APPROVED,
        opinion="审核通过.",
    ),
]

ORDERS = [
    dict(
        order_id="seed_ord001",
        buyer_id="seed_buyer001",
        seller_id="seed_seller001",
        total_amount="9999.00",
        address_snapshot="上海市静安区南京西路100号",
        phone_snapshot="13900000002",
        order_status=Order.StatusChoices.COMPLETED,
        ship_time=timezone.now(),
        receive_time=timezone.now(),
    ),
    dict(
        order_id="seed_ord002",
        buyer_id="seed_buyer002",
        seller_id="seed_seller001",
        total_amount="4998.00",
        address_snapshot="广州市天河区天河路200号",
        phone_snapshot="13900000003",
        order_status=Order.StatusChoices.SHIPPED,
        ship_time=timezone.now(),
    ),
]

ORDER_DETAILS = [
    dict(
        detail_id="seed_od001",
        order_id="seed_ord001",
        product_id="seed_prod001",
        quantity=1,
        price_snapshot="9999.00",
        subtotal="9999.00",
    ),
    dict(
        detail_id="seed_od002",
        order_id="seed_ord002",
        product_id="seed_prod002",
        quantity=2,
        price_snapshot="2499.00",
        subtotal="4998.00",
    ),
]

MESSAGES = [
    dict(
        message_id="seed_msg001",
        user_id="seed_buyer001",
        product_id="seed_prod001",
        content="请问这款手机支持双卡双待吗?",
        reply_content="您好, 支持双卡双待 (nano SIM + eSIM), 感谢关注!",
        reply_time=timezone.now(),
    ),
    dict(
        message_id="seed_msg002",
        user_id="seed_buyer002",
        product_id="seed_prod002",
        content="耳机能连接两台设备同时使用吗?",
        reply_content=None,
        reply_time=None,
    ),
]

TAGS = [
    dict(tag_id="tag_001", tag_name="新品上市", category="营销", usage_count=0),
    dict(tag_id="tag_002", tag_name="热销爆款", category="营销", usage_count=0),
    dict(tag_id="tag_003", tag_name="高性价比", category="营销", usage_count=0),
    dict(tag_id="tag_004", tag_name="高端旗舰", category="营销", usage_count=0),
    dict(tag_id="tag_005", tag_name="苹果", category="品牌", usage_count=0),
    dict(tag_id="tag_006", tag_name="索尼", category="品牌", usage_count=0),
    dict(tag_id="tag_007", tag_name="电子产品", category="品类", usage_count=0),
    dict(tag_id="tag_008", tag_name="影音娱乐", category="品类", usage_count=0),
    dict(tag_id="tag_009", tag_name="办公必备", category="品类", usage_count=0),
    dict(tag_id="tag_010", tag_name="运动健康", category="品类", usage_count=0),
    dict(tag_id="tag_011", tag_name="智能家居", category="品类", usage_count=0),
    dict(tag_id="tag_012", tag_name="便携轻巧", category="特性", usage_count=0),
    dict(tag_id="tag_013", tag_name="超长续航", category="特性", usage_count=0),
    dict(tag_id="tag_014", tag_name="主动降噪", category="特性", usage_count=0),
    dict(tag_id="tag_015", tag_name="大容量", category="特性", usage_count=0),
]

PRODUCT_TAGS = [
    dict(id=1, product_id="seed_prod001", tag_id="tag_005", weight=1.0),
    dict(id=2, product_id="seed_prod001", tag_id="tag_007", weight=1.0),
    dict(id=3, product_id="seed_prod001", tag_id="tag_004", weight=1.0),
    dict(id=4, product_id="seed_prod002", tag_id="tag_006", weight=1.0),
    dict(id=5, product_id="seed_prod002", tag_id="tag_008", weight=1.0),
    dict(id=6, product_id="seed_prod002", tag_id="tag_014", weight=1.0),
    dict(id=7, product_id="seed_prod003", tag_id="tag_009", weight=1.0),
    dict(id=8, product_id="seed_prod003", tag_id="tag_007", weight=1.0),
    dict(id=9, product_id="seed_prod004", tag_id="tag_010", weight=1.0),
    dict(id=10, product_id="seed_prod004", tag_id="tag_011", weight=1.0),
    dict(id=11, product_id="seed_prod_005", tag_id="tag_007", weight=1.0),
    dict(id=12, product_id="seed_prod_005", tag_id="tag_004", weight=1.0),
    dict(id=13, product_id="seed_prod_006", tag_id="tag_008", weight=1.0),
    dict(id=14, product_id="seed_prod_006", tag_id="tag_012", weight=1.0),
    dict(id=15, product_id="seed_prod_006", tag_id="tag_014", weight=1.0),
    dict(id=16, product_id="seed_prod_007", tag_id="tag_009", weight=1.0),
    dict(id=17, product_id="seed_prod_007", tag_id="tag_007", weight=1.0),
    dict(id=18, product_id="seed_prod_008", tag_id="tag_010", weight=1.0),
    dict(id=19, product_id="seed_prod_008", tag_id="tag_011", weight=1.0),
    dict(id=20, product_id="seed_prod_008", tag_id="tag_013", weight=1.0),
    dict(id=21, product_id="seed_prod_009", tag_id="tag_011", weight=1.0),
    dict(id=22, product_id="seed_prod_009", tag_id="tag_012", weight=1.0),
    dict(id=23, product_id="seed_prod_010", tag_id="tag_007", weight=1.0),
    dict(id=24, product_id="seed_prod_010", tag_id="tag_010", weight=1.0),
    dict(id=25, product_id="seed_prod_011", tag_id="tag_008", weight=1.0),
    dict(id=26, product_id="seed_prod_011", tag_id="tag_013", weight=1.0),
    dict(id=27, product_id="seed_prod_012", tag_id="tag_009", weight=1.0),
    dict(id=28, product_id="seed_prod_012", tag_id="tag_012", weight=1.0),
    dict(id=29, product_id="seed_prod_012", tag_id="tag_013", weight=1.0),
    dict(id=30, product_id="seed_prod_013", tag_id="tag_010", weight=1.0),
    dict(id=31, product_id="seed_prod_013", tag_id="tag_011", weight=1.0),
    dict(id=32, product_id="seed_prod_014", tag_id="tag_011", weight=1.0),
    dict(id=33, product_id="seed_prod_014", tag_id="tag_012", weight=1.0),
    dict(id=34, product_id="seed_prod_015", tag_id="tag_007", weight=1.0),
    dict(id=35, product_id="seed_prod_015", tag_id="tag_004", weight=1.0),
    dict(id=36, product_id="seed_prod_016", tag_id="tag_008", weight=1.0),
    dict(id=37, product_id="seed_prod_016", tag_id="tag_012", weight=1.0),
    dict(id=38, product_id="seed_prod_016", tag_id="tag_014", weight=1.0),
    dict(id=39, product_id="seed_prod_017", tag_id="tag_009", weight=1.0),
    dict(id=40, product_id="seed_prod_017", tag_id="tag_007", weight=1.0),
    dict(id=41, product_id="seed_prod_018", tag_id="tag_010", weight=1.0),
    dict(id=42, product_id="seed_prod_018", tag_id="tag_011", weight=1.0),
    dict(id=43, product_id="seed_prod_019", tag_id="tag_011", weight=1.0),
    dict(id=44, product_id="seed_prod_019", tag_id="tag_012", weight=1.0),
    dict(id=45, product_id="seed_prod_020", tag_id="tag_007", weight=1.0),
    dict(id=46, product_id="seed_prod_020", tag_id="tag_008", weight=1.0),
    dict(id=47, product_id="seed_prod_021", tag_id="tag_008", weight=1.0),
    dict(id=48, product_id="seed_prod_021", tag_id="tag_012", weight=1.0),
    dict(id=49, product_id="seed_prod_021", tag_id="tag_013", weight=1.0),
    dict(id=50, product_id="seed_prod_022", tag_id="tag_009", weight=1.0),
    dict(id=51, product_id="seed_prod_022", tag_id="tag_007", weight=1.0),
    dict(id=52, product_id="seed_prod_023", tag_id="tag_010", weight=1.0),
    dict(id=53, product_id="seed_prod_023", tag_id="tag_011", weight=1.0),
    dict(id=54, product_id="seed_prod_023", tag_id="tag_014", weight=1.0),
    dict(id=55, product_id="seed_prod_024", tag_id="tag_011", weight=1.0),
    dict(id=56, product_id="seed_prod_025", tag_id="tag_009", weight=1.0),
    dict(id=57, product_id="seed_prod_025", tag_id="tag_007", weight=1.0),
    dict(id=58, product_id="seed_prod_026", tag_id="tag_008", weight=1.0),
    dict(id=59, product_id="seed_prod_026", tag_id="tag_014", weight=1.0),
    dict(id=60, product_id="seed_prod_027", tag_id="tag_010", weight=1.0),
    dict(id=61, product_id="seed_prod_027", tag_id="tag_011", weight=1.0),
    dict(id=62, product_id="seed_prod_028", tag_id="tag_011", weight=1.0),
    dict(id=63, product_id="seed_prod_028", tag_id="tag_012", weight=1.0),
    dict(id=64, product_id="seed_prod_029", tag_id="tag_007", weight=1.0),
    dict(id=65, product_id="seed_prod_029", tag_id="tag_004", weight=1.0),
    dict(id=66, product_id="seed_prod_030", tag_id="tag_009", weight=1.0),
    dict(id=67, product_id="seed_prod_030", tag_id="tag_007", weight=1.0),
    dict(id=68, product_id="seed_prod_031", tag_id="tag_008", weight=1.0),
    dict(id=69, product_id="seed_prod_031", tag_id="tag_012", weight=1.0),
    dict(id=70, product_id="seed_prod_031", tag_id="tag_013", weight=1.0),
    dict(id=71, product_id="seed_prod_032", tag_id="tag_010", weight=1.0),
    dict(id=72, product_id="seed_prod_032", tag_id="tag_011", weight=1.0),
    dict(id=73, product_id="seed_prod_033", tag_id="tag_011", weight=1.0),
    dict(id=74, product_id="seed_prod_034", tag_id="tag_007", weight=1.0),
    dict(id=75, product_id="seed_prod_034", tag_id="tag_008", weight=1.0),
    dict(id=76, product_id="seed_prod_035", tag_id="tag_008", weight=1.0),
    dict(id=77, product_id="seed_prod_035", tag_id="tag_014", weight=1.0),
    dict(id=78, product_id="seed_prod_035", tag_id="tag_012", weight=1.0),
    dict(id=79, product_id="seed_prod_036", tag_id="tag_009", weight=1.0),
    dict(id=80, product_id="seed_prod_036", tag_id="tag_007", weight=1.0),
    dict(id=81, product_id="seed_prod_037", tag_id="tag_010", weight=1.0),
    dict(id=82, product_id="seed_prod_037", tag_id="tag_011", weight=1.0),
    dict(id=83, product_id="seed_prod_037", tag_id="tag_013", weight=1.0),
    dict(id=84, product_id="seed_prod_038", tag_id="tag_011", weight=1.0),
    dict(id=85, product_id="seed_prod_039", tag_id="tag_007", weight=1.0),
    dict(id=86, product_id="seed_prod_039", tag_id="tag_004", weight=1.0),
    dict(id=87, product_id="seed_prod_040", tag_id="tag_011", weight=1.0),
    dict(id=88, product_id="seed_prod_040", tag_id="tag_012", weight=1.0),
    dict(id=89, product_id="seed_prod_041", tag_id="tag_007", weight=1.0),
    dict(id=90, product_id="seed_prod_041", tag_id="tag_013", weight=1.0),
    dict(id=91, product_id="seed_prod_041", tag_id="tag_015", weight=1.0),
    dict(id=92, product_id="seed_prod_042", tag_id="tag_010", weight=1.0),
    dict(id=93, product_id="seed_prod_042", tag_id="tag_012", weight=1.0),
    dict(id=94, product_id="seed_prod_042", tag_id="tag_013", weight=1.0),
    dict(id=95, product_id="seed_prod_043", tag_id="tag_011", weight=1.0),
    dict(id=96, product_id="seed_prod_043", tag_id="tag_015", weight=1.0),
    dict(id=97, product_id="seed_prod_044", tag_id="tag_007", weight=1.0),
    dict(id=98, product_id="seed_prod_044", tag_id="tag_008", weight=1.0),
    dict(id=99, product_id="seed_prod_044", tag_id="tag_009", weight=1.0),
    dict(id=100, product_id="seed_prod_045", tag_id="tag_008", weight=1.0),
    dict(id=101, product_id="seed_prod_045", tag_id="tag_012", weight=1.0),
    dict(id=102, product_id="seed_prod_045", tag_id="tag_013", weight=1.0),
    dict(id=103, product_id="seed_prod_046", tag_id="tag_007", weight=1.0),
    dict(id=104, product_id="seed_prod_046", tag_id="tag_008", weight=1.0),
    dict(id=105, product_id="seed_prod_047", tag_id="tag_004", weight=1.0),
    dict(id=106, product_id="seed_prod_047", tag_id="tag_007", weight=1.0),
    dict(id=107, product_id="seed_prod_047", tag_id="tag_013", weight=1.0),
    dict(id=108, product_id="seed_prod_048", tag_id="tag_010", weight=1.0),
    dict(id=109, product_id="seed_prod_048", tag_id="tag_011", weight=1.0),
    dict(id=110, product_id="seed_prod_048", tag_id="tag_013", weight=1.0),
    dict(id=111, product_id="seed_prod_049", tag_id="tag_009", weight=1.0),
    dict(id=112, product_id="seed_prod_049", tag_id="tag_012", weight=1.0),
    dict(id=113, product_id="seed_prod_050", tag_id="tag_008", weight=1.0),
    dict(id=114, product_id="seed_prod_050", tag_id="tag_011", weight=1.0),
    dict(id=115, product_id="seed_prod_050", tag_id="tag_012", weight=1.0),
    dict(id=116, product_id="seed_prod_051", tag_id="tag_007", weight=1.0),
    dict(id=117, product_id="seed_prod_051", tag_id="tag_013", weight=1.0),
    dict(id=118, product_id="seed_prod_052", tag_id="tag_008", weight=1.0),
    dict(id=119, product_id="seed_prod_052", tag_id="tag_012", weight=1.0),
    dict(id=120, product_id="seed_prod_052", tag_id="tag_013", weight=1.0),
    dict(id=121, product_id="seed_prod_053", tag_id="tag_011", weight=1.0),
    dict(id=122, product_id="seed_prod_053", tag_id="tag_015", weight=1.0),
    dict(id=123, product_id="seed_prod_054", tag_id="tag_009", weight=1.0),
    dict(id=124, product_id="seed_prod_054", tag_id="tag_011", weight=1.0),
    dict(id=125, product_id="seed_prod_054", tag_id="tag_012", weight=1.0),
    dict(id=126, product_id="seed_prod_055", tag_id="tag_008", weight=1.0),
    dict(id=127, product_id="seed_prod_055", tag_id="tag_012", weight=1.0),
    dict(id=128, product_id="seed_prod_055", tag_id="tag_013", weight=1.0),
    dict(id=129, product_id="seed_prod_056", tag_id="tag_007", weight=1.0),
    dict(id=130, product_id="seed_prod_056", tag_id="tag_008", weight=1.0),
    dict(id=131, product_id="seed_prod_057", tag_id="tag_010", weight=1.0),
    dict(id=132, product_id="seed_prod_057", tag_id="tag_011", weight=1.0),
    dict(id=133, product_id="seed_prod_058", tag_id="tag_008", weight=1.0),
    dict(id=134, product_id="seed_prod_058", tag_id="tag_012", weight=1.0),
    dict(id=135, product_id="seed_prod_058", tag_id="tag_013", weight=1.0),
    dict(id=136, product_id="seed_prod_059", tag_id="tag_007", weight=1.0),
    dict(id=137, product_id="seed_prod_059", tag_id="tag_013", weight=1.0),
    dict(id=138, product_id="seed_prod_059", tag_id="tag_015", weight=1.0),
    dict(id=139, product_id="seed_prod_060", tag_id="tag_011", weight=1.0),
    dict(id=140, product_id="seed_prod_060", tag_id="tag_013", weight=1.0),
    dict(id=141, product_id="seed_prod_061", tag_id="tag_007", weight=1.0),
    dict(id=142, product_id="seed_prod_061", tag_id="tag_013", weight=1.0),
    dict(id=143, product_id="seed_prod_062", tag_id="tag_007", weight=1.0),
    dict(id=144, product_id="seed_prod_062", tag_id="tag_009", weight=1.0),
    dict(id=145, product_id="seed_prod_062", tag_id="tag_011", weight=1.0),
    dict(id=146, product_id="seed_prod_063", tag_id="tag_010", weight=1.0),
    dict(id=147, product_id="seed_prod_063", tag_id="tag_011", weight=1.0),
    dict(id=148, product_id="seed_prod_064", tag_id="tag_011", weight=1.0),
    dict(id=149, product_id="seed_prod_064", tag_id="tag_012", weight=1.0),
    dict(id=150, product_id="seed_prod_065", tag_id="tag_004", weight=1.0),
    dict(id=151, product_id="seed_prod_065", tag_id="tag_007", weight=1.0),
    dict(id=152, product_id="seed_prod_065", tag_id="tag_013", weight=1.0),
    dict(id=153, product_id="seed_prod_066", tag_id="tag_008", weight=1.0),
    dict(id=154, product_id="seed_prod_066", tag_id="tag_012", weight=1.0),
    dict(id=155, product_id="seed_prod_066", tag_id="tag_014", weight=1.0),
    dict(id=156, product_id="seed_prod_067", tag_id="tag_007", weight=1.0),
    dict(id=157, product_id="seed_prod_067", tag_id="tag_008", weight=1.0),
    dict(id=158, product_id="seed_prod_068", tag_id="tag_010", weight=1.0),
    dict(id=159, product_id="seed_prod_068", tag_id="tag_011", weight=1.0),
    dict(id=160, product_id="seed_prod_068", tag_id="tag_013", weight=1.0),
    dict(id=161, product_id="seed_prod_069", tag_id="tag_011", weight=1.0),
    dict(id=162, product_id="seed_prod_069", tag_id="tag_013", weight=1.0),
    dict(id=163, product_id="seed_prod_070", tag_id="tag_007", weight=1.0),
    dict(id=164, product_id="seed_prod_070", tag_id="tag_008", weight=1.0),
    dict(id=165, product_id="seed_prod_070", tag_id="tag_012", weight=1.0),
    dict(id=166, product_id="seed_prod_071", tag_id="tag_008", weight=1.0),
    dict(id=167, product_id="seed_prod_071", tag_id="tag_012", weight=1.0),
    dict(id=168, product_id="seed_prod_072", tag_id="tag_007", weight=1.0),
    dict(id=169, product_id="seed_prod_072", tag_id="tag_008", weight=1.0),
    dict(id=170, product_id="seed_prod_072", tag_id="tag_012", weight=1.0),
    dict(id=171, product_id="seed_prod_073", tag_id="tag_010", weight=1.0),
    dict(id=172, product_id="seed_prod_073", tag_id="tag_011", weight=1.0),
    dict(id=173, product_id="seed_prod_074", tag_id="tag_011", weight=1.0),
    dict(id=174, product_id="seed_prod_075", tag_id="tag_008", weight=1.0),
    dict(id=175, product_id="seed_prod_075", tag_id="tag_013", weight=1.0),
    dict(id=176, product_id="seed_prod_075", tag_id="tag_014", weight=1.0),
    dict(id=177, product_id="seed_prod_076", tag_id="tag_007", weight=1.0),
    dict(id=178, product_id="seed_prod_076", tag_id="tag_008", weight=1.0),
    dict(id=179, product_id="seed_prod_077", tag_id="tag_010", weight=1.0),
    dict(id=180, product_id="seed_prod_077", tag_id="tag_011", weight=1.0),
    dict(id=181, product_id="seed_prod_078", tag_id="tag_008", weight=1.0),
    dict(id=182, product_id="seed_prod_078", tag_id="tag_012", weight=1.0),
    dict(id=183, product_id="seed_prod_078", tag_id="tag_013", weight=1.0),
    dict(id=184, product_id="seed_prod_079", tag_id="tag_007", weight=1.0),
    dict(id=185, product_id="seed_prod_079", tag_id="tag_013", weight=1.0),
    dict(id=186, product_id="seed_prod_079", tag_id="tag_015", weight=1.0),
    dict(id=187, product_id="seed_prod_080", tag_id="tag_011", weight=1.0),
    dict(id=188, product_id="seed_prod_080", tag_id="tag_013", weight=1.0),
    dict(id=189, product_id="seed_prod_080", tag_id="tag_015", weight=1.0),
    dict(id=190, product_id="seed_prod_081", tag_id="tag_004", weight=1.0),
    dict(id=191, product_id="seed_prod_081", tag_id="tag_007", weight=1.0),
    dict(id=192, product_id="seed_prod_082", tag_id="tag_009", weight=1.0),
    dict(id=193, product_id="seed_prod_082", tag_id="tag_011", weight=1.0),
    dict(id=194, product_id="seed_prod_083", tag_id="tag_010", weight=1.0),
    dict(id=195, product_id="seed_prod_083", tag_id="tag_011", weight=1.0),
    dict(id=196, product_id="seed_prod_084", tag_id="tag_012", weight=1.0),
    dict(id=197, product_id="seed_prod_084", tag_id="tag_011", weight=1.0),
    dict(id=198, product_id="seed_prod_085", tag_id="tag_008", weight=1.0),
    dict(id=199, product_id="seed_prod_085", tag_id="tag_014", weight=1.0),
    dict(id=200, product_id="seed_prod_085", tag_id="tag_013", weight=1.0),
    dict(id=201, product_id="seed_prod_086", tag_id="tag_009", weight=1.0),
    dict(id=202, product_id="seed_prod_086", tag_id="tag_008", weight=1.0),
    dict(id=203, product_id="seed_prod_087", tag_id="tag_010", weight=1.0),
    dict(id=204, product_id="seed_prod_087", tag_id="tag_011", weight=1.0),
    dict(id=205, product_id="seed_prod_087", tag_id="tag_013", weight=1.0),
    dict(id=206, product_id="seed_prod_088", tag_id="tag_004", weight=1.0),
    dict(id=207, product_id="seed_prod_088", tag_id="tag_007", weight=1.0),
    dict(id=208, product_id="seed_prod_089", tag_id="tag_011", weight=1.0),
    dict(id=209, product_id="seed_prod_089", tag_id="tag_012", weight=1.0),
    dict(id=210, product_id="seed_prod_090", tag_id="tag_008", weight=1.0),
    dict(id=211, product_id="seed_prod_090", tag_id="tag_012", weight=1.0),
    dict(id=212, product_id="seed_prod_091", tag_id="tag_010", weight=1.0),
    dict(id=213, product_id="seed_prod_091", tag_id="tag_012", weight=1.0),
    dict(id=214, product_id="seed_prod_092", tag_id="tag_008", weight=1.0),
    dict(id=215, product_id="seed_prod_092", tag_id="tag_013", weight=1.0),
    dict(id=216, product_id="seed_prod_093", tag_id="tag_011", weight=1.0),
    dict(id=217, product_id="seed_prod_093", tag_id="tag_015", weight=1.0),
    dict(id=218, product_id="seed_prod_094", tag_id="tag_004", weight=1.0),
    dict(id=219, product_id="seed_prod_094", tag_id="tag_010", weight=1.0),
    dict(id=220, product_id="seed_prod_094", tag_id="tag_011", weight=1.0),
    dict(id=221, product_id="seed_prod_095", tag_id="tag_008", weight=1.0),
    dict(id=222, product_id="seed_prod_095", tag_id="tag_014", weight=1.0),
    dict(id=223, product_id="seed_prod_095", tag_id="tag_013", weight=1.0),
    dict(id=224, product_id="seed_prod_096", tag_id="tag_008", weight=1.0),
    dict(id=225, product_id="seed_prod_096", tag_id="tag_012", weight=1.0),
    dict(id=226, product_id="seed_prod_097", tag_id="tag_010", weight=1.0),
    dict(id=227, product_id="seed_prod_097", tag_id="tag_011", weight=1.0),
    dict(id=228, product_id="seed_prod_097", tag_id="tag_013", weight=1.0),
    dict(id=229, product_id="seed_prod_098", tag_id="tag_011", weight=1.0),
    dict(id=230, product_id="seed_prod_098", tag_id="tag_013", weight=1.0),
    dict(id=231, product_id="seed_prod_099", tag_id="tag_004", weight=1.0),
    dict(id=232, product_id="seed_prod_099", tag_id="tag_007", weight=1.0),
    dict(id=233, product_id="seed_prod_099", tag_id="tag_013", weight=1.0),
    dict(id=234, product_id="seed_prod_100", tag_id="tag_009", weight=1.0),
    dict(id=235, product_id="seed_prod_100", tag_id="tag_008", weight=1.0),
    dict(id=236, product_id="seed_prod_101", tag_id="tag_008", weight=1.0),
    dict(id=237, product_id="seed_prod_101", tag_id="tag_012", weight=1.0),
    dict(id=238, product_id="seed_prod_101", tag_id="tag_013", weight=1.0),
    dict(id=239, product_id="seed_prod_102", tag_id="tag_011", weight=1.0),
    dict(id=240, product_id="seed_prod_102", tag_id="tag_015", weight=1.0),
    dict(id=241, product_id="seed_prod_103", tag_id="tag_010", weight=1.0),
    dict(id=242, product_id="seed_prod_103", tag_id="tag_011", weight=1.0),
    dict(id=243, product_id="seed_prod_104", tag_id="tag_007", weight=1.0),
    dict(id=244, product_id="seed_prod_104", tag_id="tag_008", weight=1.0),
    dict(id=245, product_id="seed_prod_104", tag_id="tag_012", weight=1.0),
]

USER_TAG_PREFERENCES = [
    dict(
        id=1,
        user_id="seed_buyer001",
        tag_id="tag_001",
        score=5.0,
    ),
    dict(
        id=2,
        user_id="seed_buyer001",
        tag_id="tag_003",
        score=4.5,
    ),
    dict(
        id=3,
        user_id="seed_buyer002",
        tag_id="tag_002",
        score=3.0,
    ),
]

PRODUCT_FAVORITES = [
    dict(
        user_id="seed_buyer001",
        product_id="seed_prod001",
    ),
    dict(
        user_id="seed_buyer001",
        product_id="seed_prod002",
    ),
    dict(
        user_id="seed_buyer002",
        product_id="seed_prod002",
    ),
]


# ── 主逻辑 ────────────────────────────────────────────────────────────────────

class Command(BaseCommand):
    help = "插入前端测试种子数据 (幂等, 可重复运行)"

    def _upsert(self, model, lookup_field, records):
        created_count = 0
        for data in records:
            lookup = {lookup_field: data[lookup_field]}
            _, created = model.objects.get_or_create(
                **lookup, defaults={k: v for k, v in data.items() if k != lookup_field}
            )
            if created:
                created_count += 1
                self.stdout.write(f"  + {model.__name__}: {data[lookup_field]}")
            else:
                self.stdout.write(
                    self.style.WARNING(f"  ~ {model.__name__}: {data[lookup_field]} (已存在, 跳过)")
                )
        return created_count

    def handle(self, *args, **options):
        total = 0

        self.stdout.write(self.style.MIGRATE_HEADING("── 用户 ──"))
        total += self._upsert(User, "user_id", USERS)

        self.stdout.write(self.style.MIGRATE_HEADING("── 商品 ──"))
        total += self._upsert(Product, "product_id", PRODUCTS)

        self.stdout.write(self.style.MIGRATE_HEADING("── 注册审核 ──"))
        total += self._upsert(RegisterReview, "review_id", REGISTER_REVIEWS)

        self.stdout.write(self.style.MIGRATE_HEADING("── 商品审核 ──"))
        total += self._upsert(ProductReview, "review_id", PRODUCT_REVIEWS)

        self.stdout.write(self.style.MIGRATE_HEADING("── 订单 ──"))
        total += self._upsert(Order, "order_id", ORDERS)

        self.stdout.write(self.style.MIGRATE_HEADING("── 订单明细 ──"))
        total += self._upsert(OrderDetail, "detail_id", ORDER_DETAILS)

        self.stdout.write(self.style.MIGRATE_HEADING("── 留言 ──"))
        total += self._upsert(Message, "message_id", MESSAGES)

        self.stdout.write(self.style.MIGRATE_HEADING("── 标签 ──"))
        total += self._upsert(Tag, "tag_id", TAGS)

        self.stdout.write(self.style.MIGRATE_HEADING("── 商品标签关联 ──"))
        total += self._upsert_product_tags()

        self.stdout.write(self.style.MIGRATE_HEADING("── 用户标签偏好 ──"))
        total += self._upsert_user_tag_preferences()

        self.stdout.write(self.style.MIGRATE_HEADING("── 商品收藏 ──"))
        total += self._upsert_product_favorites()

        self.stdout.write(
            self.style.SUCCESS(f"\n完成. 共新增 {total} 条记录.")
        )

    def _upsert_product_tags(self):
        created_count = 0
        for data in PRODUCT_TAGS:
            product = Product.objects.get(product_id=data["product_id"])
            tag = Tag.objects.get(tag_id=data["tag_id"])
            _, created = ProductTag.objects.get_or_create(
                product=product,
                tag=tag,
                defaults={"weight": data["weight"]}
            )
            if created:
                created_count += 1
                self.stdout.write(f"  + ProductTag: {data['product_id']} - {data['tag_id']}")
            else:
                self.stdout.write(
                    self.style.WARNING(f"  ~ ProductTag: {data['product_id']} - {data['tag_id']} (已存在, 跳过)")
                )
        return created_count

    def _upsert_user_tag_preferences(self):
        created_count = 0
        for data in USER_TAG_PREFERENCES:
            user = User.objects.get(user_id=data["user_id"])
            tag = Tag.objects.get(tag_id=data["tag_id"])
            _, created = UserTagPreference.objects.get_or_create(
                user=user,
                tag=tag,
                defaults={"score": data["score"]}
            )
            if created:
                created_count += 1
                self.stdout.write(f"  + UserTagPreference: {data['user_id']} - {data['tag_id']}")
            else:
                self.stdout.write(
                    self.style.WARNING(f"  ~ UserTagPreference: {data['user_id']} - {data['tag_id']} (已存在, 跳过)")
                )
        return created_count

    def _upsert_product_favorites(self):
        created_count = 0
        for data in PRODUCT_FAVORITES:
            user = User.objects.get(user_id=data["user_id"])
            product = Product.objects.get(product_id=data["product_id"])
            _, created = ProductFavorite.objects.get_or_create(
                user=user,
                product=product,
            )
            if created:
                created_count += 1
                self.stdout.write(f"  + ProductFavorite: {data['user_id']} - {data['product_id']}")
            else:
                self.stdout.write(
                    self.style.WARNING(f"  ~ ProductFavorite: {data['user_id']} - {data['product_id']} (已存在, 跳过)")
                )
        return created_count
