# Generated by Django 6.0.3 on 2026-03-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='订单总金额')),
                ('address_snapshot', models.CharField(max_length=255, verbose_name='收货地址快照')),
                ('phone_snapshot', models.CharField(max_length=20, verbose_name='联系电话快照')),
                ('order_status', models.CharField(choices=[('PENDING_PAY', '待付款'), ('PENDING_SHIP', '已付款待出货'), ('SHIPPED', '已出货待收货'), ('COMPLETED', '已收货交易完成'), ('CANCELED', '已取消')], default='PENDING_PAY', max_length=20, verbose_name='订单状态')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('ship_time', models.DateTimeField(blank=True, null=True, verbose_name='出货时间')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='商品ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('category', models.CharField(max_length=100, verbose_name='商品分类')),
                ('description', models.TextField(verbose_name='详情描述')),
                ('image_url', models.URLField(max_length=500, verbose_name='商品图片地址')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销量')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('product_status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '审核通过'), ('OFF_SHELF', '已下架'), ('REJECTED', '审核驳回')], default='PENDING', max_length=20, verbose_name='商品状态')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='标签ID')),
                ('tag_name', models.CharField(max_length=100, unique=True, verbose_name='标签名称')),
                ('category', models.CharField(max_length=100, verbose_name='标签分类')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='电子邮箱')),
                ('phone', models.EmailField(max_length=254, unique=True, verbose_name='电话号码')),
                ('encrypted_password', models.CharField(max_length=255, verbose_name='加密登录密码')),
                ('real_name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('phone_display', models.CharField(max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('role', models.CharField(choices=[('NORMAL', '普通用户'), ('ADMIN', '系统管理员')], default='NORMAL', max_length=20, verbose_name='用户角色')),
                ('register_status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '审核通过'), ('REJECTED', '审核驳回')], default='PENDING', max_length=20, verbose_name='注册状态')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('detail_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单明细ID')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='下单单价快照')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小计金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.order', verbose_name='所属订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='core.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='RegisterReview',
            fields=[
                ('review_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='审查记录ID')),
                ('result', models.CharField(choices=[('APPROVED', '审核通过'), ('REJECTED', '审核驳回')], max_length=20, verbose_name='审查结果')),
                ('opinion', models.TextField(blank=True, null=True, verbose_name='审查意见')),
                ('review_time', models.DateTimeField(auto_now_add=True, verbose_name='审查时间')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_register_reviews', to='core.user', verbose_name='审查管理员')),
                ('pending_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='register_review', to='core.user', verbose_name='待审核用户')),
            ],
            options={
                'verbose_name': '注册审查记录',
                'verbose_name_plural': '注册审查记录',
                'db_table': 'register_review',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('review_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='审查记录ID')),
                ('result', models.CharField(choices=[('APPROVED', '审核通过'), ('REJECTED', '审核驳回')], max_length=20, verbose_name='审查结果')),
                ('opinion', models.TextField(blank=True, null=True, verbose_name='审查意见')),
                ('review_time', models.DateTimeField(auto_now_add=True, verbose_name='审查时间')),
                ('pending_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='core.product', verbose_name='待审核商品')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_product_reviews', to='core.user', verbose_name='审查管理员')),
            ],
            options={
                'verbose_name': '商品审查记录',
                'verbose_name_plural': '商品审查记录',
                'db_table': 'product_review',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_products', to='core.user', verbose_name='发布者用户'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_orders', to='core.user', verbose_name='买家'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_orders', to='core.user', verbose_name='卖家'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='留言ID')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('message_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('reply_content', models.TextField(blank=True, null=True, verbose_name='回复内容')),
                ('reply_time', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.product', verbose_name='关联商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.user', verbose_name='留言用户')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, verbose_name='标签权重')),
                ('tagged_time', models.DateTimeField(auto_now_add=True, verbose_name='打标时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='core.product', verbose_name='商品')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_products', to='core.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '商品标签关联',
                'verbose_name_plural': '商品标签关联',
                'db_table': 'product_tag',
                'unique_together': {('product', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品收藏',
                'verbose_name_plural': '商品收藏',
                'db_table': 'product_favorite',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='UserTagPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='偏好分数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='core.tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_preferences', to='core.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户标签偏好',
                'verbose_name_plural': '用户标签偏好',
                'db_table': 'user_tag_preference',
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
