# Generated by Django 6.0.3 on 2026-04-03 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_init_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_receive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='自动确认收货时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='取消原因'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='物流公司'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='物流信息快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='物流单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款时间'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('type', models.CharField(choices=[('ORDER', '订单通知'), ('SYSTEM', '系统通知'), ('MESSAGE', '消息通知')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.order', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.user', verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '用户通知',
                'verbose_name_plural': '用户通知',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('log_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='日志ID')),
                ('action', models.CharField(choices=[('CREATE', '创建订单'), ('PAY', '支付订单'), ('SHIP', '卖家发货'), ('RECEIVE', '确认收货'), ('CANCEL', '取消订单'), ('AUTO_COMPLETE', '自动完成')], max_length=20, verbose_name='操作类型')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_logs', to='core.user', verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单操作日志',
                'verbose_name_plural': '订单操作日志',
                'db_table': 'order_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
