# Generated by Django 6.0.3 on 2026-04-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_auto_receive_time_order_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='orderlog',
            options={'ordering': ['-created_at'], 'verbose_name': '订单日志', 'verbose_name_plural': '订单日志'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER', '订单通知'), ('SYSTEM', '系统通知'), ('MESSAGE', '消息通知')], default='ORDER', max_length=20, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics_info',
            field=models.JSONField(default=dict, verbose_name='物流信息快照'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action',
            field=models.CharField(choices=[('CREATE', '创建订单'), ('PAY', '支付订单'), ('SHIP', '发货'), ('RECEIVE', '确认收货'), ('CANCEL', '取消订单'), ('AUTO_COMPLETE', '自动完成')], max_length=50, verbose_name='操作类型'),
        ),
    ]
