# Generated by Django 6.0.3 on 2026-04-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_options_alter_orderlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': '用户通知', 'verbose_name_plural': '用户通知'},
        ),
        migrations.AlterModelOptions(
            name='orderlog',
            options={'ordering': ['-created_at'], 'verbose_name': '订单操作日志', 'verbose_name_plural': '订单操作日志'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER', '订单通知'), ('SYSTEM', '系统通知'), ('MESSAGE', '消息通知')], max_length=20, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='物流信息快照'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action',
            field=models.CharField(choices=[('CREATE', '创建订单'), ('PAY', '支付订单'), ('SHIP', '卖家发货'), ('RECEIVE', '确认收货'), ('CANCEL', '取消订单'), ('AUTO_COMPLETE', '自动完成')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='消息ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_messages', to='core.user', verbose_name='接收者')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='core.order', verbose_name='关联订单')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='core.product', verbose_name='关联商品')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to='core.user', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'chat_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'receiver'], name='chat_messag_sender__61a5fc_idx'), models.Index(fields=['receiver', 'is_read'], name='chat_messag_receive_14362e_idx'), models.Index(fields=['created_at'], name='chat_messag_created_b6b51c_idx')],
            },
        ),
    ]
