# Generated by Django 6.0.3 on 2026-04-16 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_chat_message'),
        ('core', '0007_forum_feature'),
    ]

    operations = [
    ]
